package com.dailyapps.aetherforge.ui.theme

import androidx.compose.ui.graphics.Color

val SkyBlue = Color(0xFF0EA5E9)
val SkyBlueLight = Color(0xFF38BDF8)
val DeepSlate = Color(0xFF0F172A)
val Slate800 = Color(0xFF1E293B)
val Slate700 = Color(0xFF334155)
val Emerald = Color(0xFF10B981)
val Amber = Color(0xFFF59E0B)
val Rose = Color(0xFFF43F5E)
val Violet = Color(0xFF8B5CF6)

val md_theme_light_primary = Color(0xFF0284C7)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0F2FE)
val md_theme_light_onPrimaryContainer = Color(0xFF0C4A6E)
val md_theme_light_secondary = Color(0xFF0F766E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCFBF1)
val md_theme_light_onSecondaryContainer = Color(0xFF134E4A)
val md_theme_light_tertiary = Color(0xFF7C3AED)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFE2E8F0)
val md_theme_light_onSurfaceVariant = Color(0xFF475569)

val md_theme_dark_primary = Color(0xFF38BDF8)
val md_theme_dark_onPrimary = Color(0xFF0C4A6E)
val md_theme_dark_primaryContainer = Color(0xFF0369A1)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0F2FE)
val md_theme_dark_secondary = Color(0xFF2DD4BF)
val md_theme_dark_onSecondary = Color(0xFF134E4A)
val md_theme_dark_secondaryContainer = Color(0xFF0F766E)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCFBF1)
val md_theme_dark_tertiary = Color(0xFFA78BFA)
val md_theme_dark_onTertiary = Color(0xFF4C1D95)
val md_theme_dark_background = Color(0xFF0F172A)
val md_theme_dark_onBackground = Color(0xFFF1F5F9)
val md_theme_dark_surface = Color(0xFF1E293B)
val md_theme_dark_onSurface = Color(0xFFF1F5F9)
val md_theme_dark_surfaceVariant = Color(0xFF334155)
val md_theme_dark_onSurfaceVariant = Color(0xFFCBD5E1)
